/* 読み上げに使う声のファイル（tools/make_voice.py が自動で作る。手で直さない）
 * 文がこの表とぴったり同じとき（空白のちがいは気にしない）に、この音声を使う。無い文はブラウザが読み上げる。
 * 「nyu:」で はじまるものは ニューちゃんの 声。 */
window.G = window.G || {};

G.VOICE_CLIPS = {
  "にゃっほー！ きょうも あそびに きてくれた ニャー！": 'assets/voice/m_greetDaily.m4a',
  "おかえり！ また あえて うれしい ニャー": 'assets/voice/m_greetAgain_1.m4a',
  "にゃっほー！ いっしょに あそぼ ニャー": 'assets/voice/m_greetAgain_2.m4a',
  "おなか ぺこぺこ ニャー…": 'assets/voice/m_hungry.m4a',
  "からだを きれいに したい ニャー": 'assets/voice/m_dirty.m4a',
  "ねえねえ、 いっしょに あそぼ ニャー？": 'assets/voice/m_bored.m4a',
  "ふぁ〜あ、 ねむく なっちゃった ニャー": 'assets/voice/m_sleepy.m4a',
  "おひさま ぽかぽか ニャー": 'assets/voice/m_content_1.m4a',
  "きょうも いい きもち ニャー！": 'assets/voice/m_content_2.m4a',
  "わたし、 おさかなが だいすき ニャー": 'assets/voice/m_content_3.m4a',
  "なでなで してくれる ニャー？": 'assets/voice/m_content_4.m4a',
  "ピアノの おと、 すき ニャー": 'assets/voice/m_content_5.m4a',
  "きもちいい ニャー〜": 'assets/voice/m_pet_2.m4a',
  "うふふ、 くすぐったい ニャー": 'assets/voice/m_pet_3.m4a',
  "もう おなか いっぱい ニャー！": 'assets/voice/m_fullFood.m4a',
  "まだ ぴかぴか ニャー！": 'assets/voice/m_fullBath.m4a',
  "どれを たべさせて くれる ニャー？": 'assets/voice/m_foodIntro.m4a',
  "ごはんを おくちに もってきて ニャー": 'assets/voice/m_foodHint.m4a',
  "もぐもぐ ニャー": 'assets/voice/m_foodEat.m4a',
  "ぺろり！ おいしかった ニャー！": 'assets/voice/m_foodDone.m4a',
  "これ だいすき！ ありがとう ニャー！": 'assets/voice/m_foodFav.m4a',
  "あわあわ ニャー〜！": 'assets/voice/m_bathFoam.m4a',
  "タオルで ふきふき して ニャー": 'assets/voice/m_bathTowel.m4a',
  "ぴかぴかで ふわふわ ニャー！": 'assets/voice/m_bathDone.m4a',
  "なにして あそぶ ニャー？": 'assets/voice/m_playIntro.m4a',
  "けいとだまを タッチして ニャー": 'assets/voice/m_yarnIntro.m4a',
  "まてまて ニャー〜！": 'assets/voice/m_yarnCheer_1.m4a',
  "えいっ ニャー！": 'assets/voice/m_yarnCheer_2.m4a',
  "つかまえた ニャー！": 'assets/voice/m_yarnCheer_3.m4a',
  "ころころ ニャー〜！": 'assets/voice/m_yarnCheer_4.m4a',
  "すごい！ たのしかった ニャー！": 'assets/voice/m_yarnDone.m4a',
  "ねこじゃらしを ゆびで うごかして ニャー": 'assets/voice/m_teaserIntro.m4a',
  "にゃっ ニャー！": 'assets/voice/m_teaserCheer_1.m4a',
  "たのしかった！ ねこじゃらし だいすき ニャー": 'assets/voice/m_teaserDone.m4a',
  "すきな いろで おえかき して ニャー": 'assets/voice/m_drawIntro.m4a',
  "nyu:きもちいい ニャー〜": 'assets/voice/n_pet_2.m4a',
  "nyu:もっと なでて ニャー！": 'assets/voice/n_pet_3.m4a',
  "nyu:おみやげ もってきた ニャー！": 'assets/voice/n_gift.m4a',
  "nyu:おねえちゃん、 いっしょに あそぼ ニャー！": 'assets/voice/n_chat_1.m4a',
  "nyu:ニューも おなか すいた ニャー": 'assets/voice/n_chat_2.m4a',
  "nyu:この おへや、 すき ニャー": 'assets/voice/n_chat_3.m4a',
  "nyu:おねえちゃんの まね ニャー！": 'assets/voice/n_chat_4.m4a',
  "nyu:おねえちゃん、 かわいい ニャー！": 'assets/voice/n_praise.m4a',
  "nyu:おねえちゃんと おそろい ニャー！": 'assets/voice/n_osoroi.m4a',
  "nyu:おかえり ニャー！": 'assets/voice/n_welcome.m4a',
  "nyu:そろそろ かえる。 また くる ニャー！": 'assets/voice/n_leave.m4a',
  "nyu:またね ニャー！": 'assets/voice/n_bye.m4a',
  "まえの リボン": 'assets/voice/g_ribbon_prev.m4a',
  "ぜんぶ あつめたよ！": 'assets/voice/g_stickers_all.m4a',
  "けしゴム": 'assets/voice/g_draw_eraser.m4a',
  "ぜんぶ けす": 'assets/voice/g_draw_clear.m4a',
  "できた": 'assets/voice/g_draw_done.m4a',
  "アルバム": 'assets/voice/g_album.m4a',
  "とじる": 'assets/voice/g_album_close.m4a'
};
