/* 読み上げに使う声のファイル（tools/make_voice.py が自動で作る。手で直さない）
 * 文がこの表とぴったり同じとき（空白のちがいは気にしない）に、この音声を使う。無い文はブラウザが読み上げる。
 * 「nyu:」で はじまるものは ニューちゃんの 声。 */
window.G = window.G || {};

G.VOICE_CLIPS = {
  "にゃっほー！ きょうも あそびに きてくれた ニャー！": 'assets/voice/m_greetDaily.m4a',
  "おかえり！ また あえて うれしい ニャー": 'assets/voice/m_greetAgain_1.m4a',
  "にゃっほー！ いっしょに あそぼ ニャー": 'assets/voice/m_greetAgain_2.m4a',
  "おなか ぺこぺこ ニャー…": 'assets/voice/m_hungry.m4a',
  "からだを きれいに したい ニャー": 'assets/voice/m_dirty.m4a',
  "ねえねえ、 いっしょに あそぼ ニャー？": 'assets/voice/m_bored.m4a',
  "ふぁ〜あ、 ねむく なっちゃった ニャー": 'assets/voice/m_sleepy.m4a',
  "さみしい ニャー…": 'assets/voice/m_lonely.m4a',
  "おひさま ぽかぽか ニャー": 'assets/voice/m_content_1.m4a',
  "きょうも いい きもち ニャー！": 'assets/voice/m_content_2.m4a',
  "わたし、 おさかなが だいすき ニャー": 'assets/voice/m_content_3.m4a',
  "なでなで してくれる ニャー？": 'assets/voice/m_content_4.m4a',
  "ピアノの おと、 すき ニャー": 'assets/voice/m_content_5.m4a',
  "ゴロゴロ ニャー…": 'assets/voice/m_pet_1.m4a',
  "きもちいい ニャー〜": 'assets/voice/m_pet_2.m4a',
  "うふふ、 くすぐったい ニャー": 'assets/voice/m_pet_3.m4a',
  "もう おなか いっぱい ニャー！": 'assets/voice/m_fullFood.m4a',
  "まだ ぴかぴか ニャー！": 'assets/voice/m_fullBath.m4a',
  "まだ ねむくない。 げんき いっぱい ニャー！": 'assets/voice/m_fullSleep.m4a',
  "どれを たべさせて くれる ニャー？": 'assets/voice/m_foodIntro.m4a',
  "ごはんを おくちに もってきて ニャー": 'assets/voice/m_foodHint.m4a',
  "もぐもぐ ニャー": 'assets/voice/m_foodEat.m4a',
  "ぺろり！ おいしかった ニャー！": 'assets/voice/m_foodDone.m4a',
  "これ だいすき！ ありがとう ニャー！": 'assets/voice/m_foodFav.m4a',
  "どっちの せっけんで あらう ニャー？": 'assets/voice/m_bathIntro.m4a',
  "あわあわ ニャー〜！": 'assets/voice/m_bathFoam.m4a',
  "じゃぐちを タッチして ニャー": 'assets/voice/m_bathShower.m4a',
  "あわを ゆびで ながして ニャー": 'assets/voice/m_bathRinse.m4a',
  "すきな おもちゃで あそんで ニャー": 'assets/voice/m_bathToy.m4a',
  "ぷかぷか ニャー！": 'assets/voice/m_bathToyCheer_1.m4a',
  "たのしい ニャー〜！": 'assets/voice/m_bathToyCheer_2.m4a',
  "もっと あそぼ ニャー！": 'assets/voice/m_bathToyCheer_3.m4a',
  "タオルで ふきふき して ニャー": 'assets/voice/m_bathTowel.m4a',
  "ぴかぴかで ふわふわ ニャー！": 'assets/voice/m_bathDone.m4a',
  "なにして あそぶ ニャー？": 'assets/voice/m_playIntro.m4a',
  "けいとだまを タッチして ニャー": 'assets/voice/m_yarnIntro.m4a',
  "まてまて ニャー〜！": 'assets/voice/m_yarnCheer_1.m4a',
  "えいっ ニャー！": 'assets/voice/m_yarnCheer_2.m4a',
  "つかまえた ニャー！": 'assets/voice/m_yarnCheer_3.m4a',
  "ころころ ニャー〜！": 'assets/voice/m_yarnCheer_4.m4a',
  "すごい！ たのしかった ニャー！": 'assets/voice/m_yarnDone.m4a',
  "ネズミの おもちゃを タッチして ニャー": 'assets/voice/m_mouseIntro.m4a',
  "すばしっこい ニャー！": 'assets/voice/m_mouseCheer_4.m4a',
  "ネズミの おもちゃ、 たのしかった ニャー！": 'assets/voice/m_mouseDone.m4a',
  "ねこじゃらしを ゆびで うごかして ニャー": 'assets/voice/m_teaserIntro.m4a',
  "にゃっ ニャー！": 'assets/voice/m_teaserCheer_1.m4a',
  "たのしかった！ ねこじゃらし だいすき ニャー": 'assets/voice/m_teaserDone.m4a',
  "すきな いろで おえかき して ニャー": 'assets/voice/m_drawIntro.m4a',
  "なにか かいてみて ニャー": 'assets/voice/m_drawEmpty.m4a',
  "もう いちど おすと ぜんぶ きえる ニャー": 'assets/voice/m_drawClear.m4a',
  "じょうず ニャー！": 'assets/voice/m_drawCheer_1.m4a',
  "すてきな いろ ニャー！": 'assets/voice/m_drawCheer_2.m4a',
  "わあ、 なにかな ニャー？": 'assets/voice/m_drawCheer_3.m4a',
  "すてきな え！ おへやに かざる ニャー": 'assets/voice/m_drawDone.m4a',
  "かいてくれた え、 だいすき ニャー": 'assets/voice/m_drawWall.m4a',
  "しゃしんを とって くれるの？ カメラの ボタンを おして ニャー": 'assets/voice/m_photoIntro.m4a',
  "にっこり ニャー！": 'assets/voice/m_photoPose_1.m4a',
  "おすまし ニャー": 'assets/voice/m_photoPose_2.m4a',
  "バイバイ ニャー！": 'assets/voice/m_photoPose_3.m4a',
  "うっとり ニャー": 'assets/voice/m_photoPose_4.m4a',
  "かわいく とれた ニャー？": 'assets/voice/m_photoSnap_1.m4a',
  "もう いちまい ニャー！": 'assets/voice/m_photoSnap_2.m4a',
  "すてき ニャー！": 'assets/voice/m_photoSnap_3.m4a',
  "しゃしんが いっぱい！ アルバムに しまった ニャー": 'assets/voice/m_photoDone.m4a',
  "まだ しゃしんが ない ニャー": 'assets/voice/m_albumEmpty.m4a',
  "ベッドを タッチして ニャー": 'assets/voice/m_sleepIntro.m4a',
  "おやすみなさい ニャー…": 'assets/voice/m_sleepGo.m4a',
  "おはよう！ げんき いっぱい ニャー！": 'assets/voice/m_sleepWake.m4a',
  "もう おやすみの じかん。 また あした ニャー": 'assets/voice/m_sleepNight.m4a',
  "どの リボンに しようかな ニャー？": 'assets/voice/m_dressIntro.m4a',
  "じゃーん！ にあってる ニャー？": 'assets/voice/m_dressDone.m4a',
  "ハートを あつめると つけられる ニャー": 'assets/voice/m_dressLocked.m4a',
  "どの ふくを きようかな ニャー？": 'assets/voice/m_clothesIntro.m4a',
  "この ふく、 すき ニャー！": 'assets/voice/m_clothesDone_2.m4a',
  "くるっと まわって… どう ニャー？": 'assets/voice/m_clothesDone_3.m4a',
  "この いろも すてき ニャー": 'assets/voice/m_clothesColor.m4a',
  "ぬいだ ニャー": 'assets/voice/m_clothesOff.m4a',
  "いまは なにも きて ない ニャー": 'assets/voice/m_clothesNone.m4a',
  "どれを つけて みる ニャー？": 'assets/voice/m_accIntro.m4a',
  "わあ、 かわいい！ ありがとう ニャー！": 'assets/voice/m_accDone_2.m4a',
  "うふふ、 すてき ニャー？": 'assets/voice/m_accDone_3.m4a',
  "はずした ニャー": 'assets/voice/m_accOff.m4a',
  "まだ なにも つけて ない ニャー": 'assets/voice/m_accNone.m4a',
  "メイク して くれるの？ うれしい ニャー": 'assets/voice/m_makeupIntro.m4a',
  "すきな いろを えらんで ニャー": 'assets/voice/m_makeupPick.m4a',
  "ほっぺを ポンポン して ニャー": 'assets/voice/m_cheekHint.m4a',
  "おくちに ぬりぬり して ニャー": 'assets/voice/m_lipHint.m4a',
  "めの うえを なでなで して ニャー": 'assets/voice/m_eyeHint.m4a',
  "すてき！ かわいく なった ニャー？": 'assets/voice/m_makeupDone_1.m4a',
  "わあ、 おひめさまみたい ニャー！": 'assets/voice/m_makeupDone_2.m4a',
  "ありがとう！ うれしい ニャー！": 'assets/voice/m_makeupDone_3.m4a',
  "もう ついてる。 ほかの いろも ためしてみる ニャー？": 'assets/voice/m_makeupAgain.m4a',
  "コットンで ふきふき して ニャー": 'assets/voice/m_makeupRemove.m4a',
  "さっぱり した ニャー！": 'assets/voice/m_makeupRemoved.m4a',
  "まだ なにも ついて ない ニャー": 'assets/voice/m_makeupNone.m4a',
  "ハートを あつめると つかえる ニャー": 'assets/voice/m_makeupLocked.m4a',
  "また あそびに きてね ニャー！": 'assets/voice/m_bye.m4a',
  "きょうは ここまで。 また あした ニャー": 'assets/voice/m_limit.m4a',
  "ニューちゃん、 いらっしゃい ニャー！": 'assets/voice/m_nyuWelcome.m4a',
  "わたしの いもうとの ニューちゃん ニャー！": 'assets/voice/m_nyuIntro.m4a',
  "いいよ ニャー！": 'assets/voice/m_nyuReply_1.m4a',
  "うふふ ニャー": 'assets/voice/m_nyuReply_2.m4a',
  "ニューちゃん、 かわいい ニャー": 'assets/voice/m_nyuReply_3.m4a',
  "ありがとう ニャー！": 'assets/voice/m_nyuThanks.m4a',
  "えへへ ニャー": 'assets/voice/m_nyuShy.m4a',
  "また きてね ニャー！": 'assets/voice/m_nyuBye.m4a',
  "シールを もらった ニャー！": 'assets/voice/m_stickerGet.m4a',
  "あたらしい リボンが ふえた ニャー！": 'assets/voice/m_unlockGet.m4a',
  "きょうの ごあいさつ ニャー": 'assets/voice/m_dailyHeart.m4a',
  "nyu:こんにちは！ あそびに きた ニャー！": 'assets/voice/n_arrive_1.m4a',
  "nyu:おねえちゃん！ あそびに きた ニャー！": 'assets/voice/n_arrive_2.m4a',
  "nyu:ニューだよ。 よろしく ニャー！": 'assets/voice/n_hello.m4a',
  "nyu:えへへ、 くすぐったい ニャー": 'assets/voice/n_pet_1.m4a',
  "nyu:きもちいい ニャー〜": 'assets/voice/n_pet_2.m4a',
  "nyu:もっと なでて ニャー！": 'assets/voice/n_pet_3.m4a',
  "nyu:おみやげ もってきた ニャー！": 'assets/voice/n_gift.m4a',
  "nyu:おねえちゃん、 いっしょに あそぼ ニャー！": 'assets/voice/n_chat_1.m4a',
  "nyu:ニューも おなか すいた ニャー": 'assets/voice/n_chat_2.m4a',
  "nyu:この おへや、 すき ニャー": 'assets/voice/n_chat_3.m4a',
  "nyu:おねえちゃんの まね ニャー！": 'assets/voice/n_chat_4.m4a',
  "nyu:おねえちゃん、 かわいい ニャー！": 'assets/voice/n_praise.m4a',
  "nyu:おねえちゃんと おそろい ニャー！": 'assets/voice/n_osoroi.m4a',
  "nyu:おかえり ニャー！": 'assets/voice/n_welcome.m4a',
  "nyu:そろそろ かえる。 また くる ニャー！": 'assets/voice/n_leave.m4a',
  "nyu:またね ニャー！": 'assets/voice/n_bye.m4a',
  "nyu:ニューも いっしょに いく ニャー！": 'assets/voice/n_outing.m4a',
  "nyu:おねえちゃん、 いらっしゃい ニャー！": 'assets/voice/n_homeHello.m4a',
  "まえの リボン": 'assets/voice/g_ribbon_prev.m4a',
  "ぜんぶ あつめたよ！": 'assets/voice/g_stickers_all.m4a',
  "けしゴム": 'assets/voice/g_draw_eraser.m4a',
  "ぜんぶ けす": 'assets/voice/g_draw_clear.m4a',
  "できた": 'assets/voice/g_draw_done.m4a',
  "アルバム": 'assets/voice/g_album.m4a',
  "とじる": 'assets/voice/g_album_close.m4a',
  "シールを もらったよ！ クロワッサン": 'assets/voice/m_get_sticker_01.m4a',
  "シールを もらったよ！ リボン": 'assets/voice/m_get_sticker_02.m4a',
  "シールを もらったよ！ おさかな": 'assets/voice/m_get_sticker_03.m4a',
  "シールを もらったよ！ ピアノ": 'assets/voice/m_get_sticker_04.m4a',
  "シールを もらったよ！ ミルク": 'assets/voice/m_get_sticker_05.m4a',
  "シールを もらったよ！ カップケーキ": 'assets/voice/m_get_sticker_06.m4a',
  "シールを もらったよ！ ちょうちょ": 'assets/voice/m_get_sticker_07.m4a',
  "シールを もらったよ！ おほしさま": 'assets/voice/m_get_sticker_08.m4a',
  "シールを もらったよ！ おつきさま": 'assets/voice/m_get_sticker_09.m4a',
  "シールを もらったよ！ ケーキ": 'assets/voice/m_get_sticker_10.m4a',
  "シールを もらったよ！ けいとだま": 'assets/voice/m_get_sticker_11.m4a',
  "シールを もらったよ！ かんむり": 'assets/voice/m_get_sticker_12.m4a',
  "シールを もらったよ！ にじ": 'assets/voice/m_get_sticker_13.m4a',
  "シールを もらったよ！ おはな": 'assets/voice/m_get_sticker_14.m4a',
  "シールを もらったよ！ あしあと": 'assets/voice/m_get_sticker_15.m4a',
  "シールを もらったよ！ おんぷ": 'assets/voice/m_get_sticker_16.m4a',
  "シールを もらったよ！ ほうせき": 'assets/voice/m_get_sticker_17.m4a',
  "シールを もらったよ！ いちご": 'assets/voice/m_get_sticker_18.m4a',
  "シールを もらったよ！ ティーポット": 'assets/voice/m_get_sticker_19.m4a',
  "シールを もらったよ！ おひさま": 'assets/voice/m_get_sticker_20.m4a',
  "あたらしい リボンが ふえたよ！ むらさき": 'assets/voice/m_get_ribbon_purple.m4a',
  "あたらしい リボンが ふえたよ！ みどり": 'assets/voice/m_get_ribbon_mint.m4a',
  "あたらしい リボンが ふえたよ！ みずたま": 'assets/voice/m_get_ribbon_polka.m4a',
  "あたらしい リボンが ふえたよ！ きんいろ": 'assets/voice/m_get_ribbon_gold.m4a'
};
